### ISSUE TITLE
Documentation is not building anymore: enddtdd is missing?

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#252]
https://circleci.com/gh/meteor/blaze/274

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 100, Column 2]
  unknown block tag: enddtdd
    at Object.exports.prettifyError (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/nunjucks/src/environment.js:469:27)
    at Obj.extend.renderString (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/nunjucks/src/environment.js:327:21)
    at /home/ubuntu/blaze/site/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/home/ubuntu/blaze/site/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/ubuntu/blaze/site/node_modules/hexo/lib/hexo/post.js:253:16)
    at /home/ubuntu/blaze/site/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/blaze/site/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
FATAL (unknown path) [Line 100, Column 2]
  unknown block tag: enddtdd
```

**Comment by distalx** [comment]
removing `node_modules` from site and reinstalling it, resolved the issue for me on local environment.

**Comment by mitar** [comment]
I would assume `node_modules` are recreated every time documentation is build?

**Comment by distalx** [comment]
Yes, So triggering the rebuild process without cache could solve this issue.

**Comment by mitar** [comment]
OK, triggered rebuild without cache. Let's see.

**Comment by mitar** [comment]
It seems it went through now?

**Comment by distalx** [comment]
After reading few more issues of hexojs it seems like that the `unknown block tag: enddtdd`, bug was introduced in version `3.3.5` and it's been resolved in later version.
This could be the reason that the build 275 went through.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
