### ISSUE TITLE
ReferenceError: SpacebarsCompiler is not defined

### ISSUE THREAD

**Issue by frankwo1** [meteor/blaze#363]
Hi, I am using Meteor and upgrading from version 2.1.2 to 2.2.1 and it is giving me an error that seems to be originating in spacebars package - can you help ? 
Messages below:

Upgraded the packages
accounts-base          upgraded from 1.8.0 to 1.9.0
babel-compiler         upgraded from 7.6.0 to 7.6.1
blaze                  upgraded from 2.3.4 to 2.4.0
blaze-tools            upgraded from 1.0.10 to 1.1.0
caching-html-compiler  upgraded from 1.1.2 to 1.2.0
ecmascript             upgraded from 0.15.0 to 0.15.1
html-tools             upgraded from 1.0.11 to 1.1.0
htmljs                 upgraded from 1.0.11 to 1.1.0
launch-screen          upgraded from 1.2.0 to 1.2.1
minimongo              upgraded from 1.6.1 to 1.6.2
mongo                  upgraded from 1.10.1 to 1.11.0
npm-mongo              upgraded from 3.8.1 to 3.9.0
spacebars              upgraded from 1.0.15 to 1.1.0
spacebars-compiler     upgraded from 1.1.3 to 1.2.0
templating             upgraded from 1.3.2 to 1.4.0
templating-compiler    upgraded from 1.3.3 to 1.4.0
templating-runtime     upgraded from 1.3.2 to 1.4.0
templating-tools       upgraded from 1.1.2 to 1.2.0
webapp                 upgraded from 1.10.0 to 1.10.1

Then error
W20220226-07:41:43.135(-5)? (STDERR) 						^
W20220226-07:41:43.136(-5)? (STDERR) 
W20220226-07:41:43.136(-5)? (STDERR) ReferenceError: SpacebarsCompiler is not defined
W20220226-07:41:43.136(-5)? (STDERR)     at packages/meteorhacks_ssr.js:195:18
W20220226-07:41:43.136(-5)? (STDERR)     at packages/meteorhacks_ssr.js:226:4
W20220226-07:41:43.136(-5)? (STDERR)     at packages/meteorhacks_ssr.js:235:3
W20220226-07:41:43.136(-5)? (STDERR)     at /Users/.meteor/local/build/programs/server/boot.js:401:38
W20220226-07:41:43.137(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20220226-07:41:43.137(-5)? (STDERR)     at /Users/.meteor/local/build/programs/server/boot.js:226:21
W20220226-07:41:43.137(-5)? (STDERR)     at /Users/.meteor/local/build/programs/server/boot.js:464:7
W20220226-07:41:43.137(-5)? (STDERR)     at Function.run (/Users/.meteor/local/build/programs/server/profile.js:280:14)
W20220226-07:41:43.137(-5)? (STDERR)     at /Users/.meteor/local/build/programs/server/boot.js:463:13
=> Exited with code: 1

**Comment by frankwo1** [comment]
Thanks - I got it  added to .meteor/packages
html-tools@1.1.1.
blaze-tools@1.1.1.
spacebars-compiler@1.2.1.
