### ISSUE TITLE
SSR is broken in 2.6.0

### ISSUE THREAD

**Issue by guncebektas** [meteor/blaze#384]
Especially we had been using our custom class to eliminate external packages like ```meteorhacks:ssr``` It was simple and solves the problem. But the recent update of the blaze 2.6.0 broke the solution.

I think the SSR should be a part of blaze. I really want to hear your thoughts about it. If you decide to remove it and recommend a better way to send HTML emails. I will be glad to hear. Anyway, thank you for your all efforts and love for the blaze. 

```
import {SpacebarsCompiler} from 'meteor/spacebars-compiler';
import {Blaze} from 'meteor/blaze';

class SsrService
{
  render(templateName, data) {
    const renderFunc = (data) ? Blaze.toHTMLWithData : Blaze.toHTML;
    const template = Blaze.Template[templateName];

    if(!template) {
      throw new Error(`Template ${templateName} not found`);
    }
    else {
      return renderFunc(template, data);
    }
  }

  compileTemplate(name, content) {
    // line 19 where errors pops
    const renderFunction = eval(`(function(view)
    {
      return ${SpacebarsCompiler.compile(content)}();
    })`);

    const template = new Blaze.Template(name, function() {
      return renderFunction(this);
    });

    Blaze.Template[name] = template;

    return template;
  }
}

export const SSR = new SsrService();
```

```
Meteor.defer(() => {
  SSR.compileTemplate('htmlEmail', Assets.getText(`email.html`));

  Email.send({
    to: email,
    from: MAIL.EMAIL,
    subject: subject,
    html: SSR.render('htmlEmail', emailData)
  });
});
```

The error I got at line 19 is SsrService's compileTemplate method
```
Exception in defer callback: ReferenceError: Spacebars is not defined
I20220725-14:34:00.873(3)?     at Blaze.View.eval [as _render] (eval at compileTemplate (server/shared/services/ssrService.js:19:28), <anonymous>:13:5)
I20220725-14:34:00.874(3)?     at packages/blaze/view.js:420:17
I20220725-14:34:00.874(3)?     at Object.Blaze._withCurrentView (packages/blaze/view.js:533:12)
I20220725-14:34:00.874(3)?     at Object.Blaze._expandView (packages/blaze/view.js:419:22)
I20220725-14:34:00.874(3)?     at HTMLVisitorSubtype.visitObject (packages/blaze/view.js:444:20)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visit (packages/htmljs/visitors.js:74:31)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visitArray (packages/htmljs/visitors.js:111:26)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visitChildren (packages/htmljs/visitors.js:153:17)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visitTag (packages/htmljs/visitors.js:140:28)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visit (packages/htmljs/visitors.js:59:32)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visitArray (packages/htmljs/visitors.js:111:26)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visitChildren (packages/htmljs/visitors.js:153:17)
I20220725-14:34:00.875(3)?     at HTMLVisitorSubtype.visitTag (packages/htmljs/visitors.js:140:28)
I20220725-14:34:00.876(3)?     at HTMLVisitorSubtype.visit (packages/htmljs/visitors.js:59:32)
I20220725-14:34:00.876(3)?     at HTMLVisitorSubtype.visitArray (packages/htmljs/visitors.js:111:26)
I20220725-14:34:00.876(3)?     at HTMLVisitorSubtype.visitChildren (packages/htmljs/visitors.js:153:17)
I20220725-14:34:00.876(3)?     at HTMLVisitorSubtype.visitTag (packages/htmljs/visitors.js:140:28)
I20220725-14:34:00.876(3)?     at HTMLVisitorSubtype.visit (packages/htmljs/visitors.js:59:32)
I20220725-14:34:00.876(3)?     at HTMLVisitorSubtype.visitArray (packages/htmljs/visitors.js:111:26)
I20220725-14:34:00.876(3)?     at HTMLVisitorSubtype.visit (packages/htmljs/visitors.js:72:32)
I20220725-14:34:00.876(3)?     at Object.Blaze._expand (packages/blaze/view.js:478:32)
I20220725-14:34:00.877(3)?     at Object.Blaze._expandView (packages/blaze/view.js:424:22)

```

I read the recent changes on blaze's source code but couldn't be sure why changing Spacebars with Blaze caused the error.

_Originally posted by @guncebektas in https://github.com/meteor/meteor/discussions/12071#discussioncomment-3221386_

**Comment by jankapunkt** [comment]
Hey @guncebektas thank you for pointing this out. Can you please add some minimal example for the `email.html` file so I can better replicate this? It's fine if this is some generic one, just want to grasp the inner Template logic for some further tests.

**Comment by guncebektas** [comment]
Here it is

```
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{from}}</title>
      <style type="text/css">
         /* Client-specific Styles */
         #outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
         body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; background-color: #f9fafa;}
         /* Prevent Webkit and Windows Mobile platforms from changing default font sizes, while not breaking desktop design. */
         .ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
         .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;} /* Force Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
         #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
         img {outline:none; text-decoration:none;border:none; -ms-interpolation-mode: bicubic;}
         a img {border:none;}
         .image_fix {display:block;}
         p {margin: 0 !important;}

         table td {border-collapse: collapse;}
         table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }
         /*a {color: #e95353;text-decoration: none;text-decoration:none!important;}*/
         /*STYLES*/
         table[class=full] { width: 100%; clear: both; }

         /*################################################*/
         /*IPAD STYLES*/
         /*################################################*/
         @media only screen and (max-width: 640px) {
         a[href^="tel"], a[href^="sms"] {
         text-decoration: none;
         color: #ffffff; /* or whatever your want */
         pointer-events: none;
         cursor: default;
         }
         .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
         text-decoration: default;
         color: #ffffff !important;
         pointer-events: auto;
         cursor: default;
         }
         table[class=devicewidth] {width: 440px!important;text-align:center!important;}
         table[class=devicewidthinner] {width: 420px!important;text-align:center!important;}
         table[class="sthide"]{display: none!important;}
         img[class="bigimage"]{width: 420px!important;height:219px!important;}
         img[class="col2img"]{width: 420px!important;height:258px!important;}
         img[class="image-banner"]{width: 440px!important;height:106px!important;}
         td[class="menu"]{text-align:center !important; padding: 0 0 10px 0 !important;}
         td[class="logo"]{padding:10px 0 5px 0!important;margin: 0 auto !important;}
         img[class="logo"]{padding:0!important;margin: 0 auto !important;}

         }
         /*##############################################*/
         /*IPHONE STYLES*/
         /*##############################################*/
         @media only screen and (max-width: 480px) {
         a[href^="tel"], a[href^="sms"] {
         text-decoration: none;
         color: #ffffff; /* or whatever your want */
         pointer-events: none;
         cursor: default;
         }
         .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
         text-decoration: default;
         color: #ffffff !important;
         pointer-events: auto;
         cursor: default;
         }
         table[class=devicewidth] {width: 280px!important;text-align:center!important;}
         table[class=devicewidthinner] {width: 260px!important;text-align:center!important;}
         table[class="sthide"]{display: none!important;}
         img[class="bigimage"]{width: 260px!important;height:136px!important;}
         img[class="col2img"]{width: 260px!important;height:160px!important;}
         img[class="image-banner"]{width: 280px!important;height:68px!important;}

         }
      </style>


   </head>
   <body style="font-family: Helvetica, Arial, sans-serif;">
      <div class="block">
         <!-- start of header -->
         <table width="100%" bgcolor="#0033a0" cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="header">
            <tbody>
               <tr>
                  <td>
                     <table width="580" bgcolor="#0033a0" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth" hlitebg="edit" shadow="edit">
                        <tbody>
                           <tr>
                              <td>
                                 <!-- menu -->
                                 <table width="280" cellpadding="0" cellspacing="0" border="0" align="right" class="devicewidth">
                                    <tbody>
                                       <tr>
                                          <td width="270" valign="middle" style="font-size: 14px; color: #fbfbfb;line-height: 20px; padding: 14px 0;" align="right" class="menu" st-content="menu">
                                             <a href="http://ritapos.com/" style="text-decoration: none; color: #fbfbfb;">Ritapos</a>
                                             <!--
                                             &nbsp;|&nbsp;
                                             <a href="http://ritapos.com/contact" style="text-decoration: none; color: #ffffff;">İLETİŞİM</a>
                                          -->
                                          </td>
                                          <td width="20"></td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <!-- menu -->
                              </td>
                           </tr>
                        </tbody>
                     </table>
                  </td>
               </tr>
            </tbody>
         </table>
         <!-- end of header -->
      </div>
      <div class="block">
         <!-- image + text -->
         <table width="100%" bgcolor="#0033a0" cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="bigimage">
            <tbody>
               <tr>
                  <td>
                     <table bgcolor="#ffffff" width="580" align="center" cellspacing="0" cellpadding="0" border="0" class="devicewidth" modulebg="edit">
                        <tbody>
                           <tr>
                              <td width="100%" height="10"></td>
                           </tr>
                           <tr>
                              <td>
                                 <table width="540" align="center" cellspacing="0" cellpadding="0" border="0" class="devicewidthinner">
                                    <tbody>
                                       <!-- Spacing -->
                                       <tr>
                                          <td width="100%" height="20" style="text-align: center;">
                                            <center>
                                             <a href="https://ritapos.com/"><img src="https://files.ritapos.com/logo.png" alt="logo" border="0" style="display:block; border:none; outline:none; text-decoration:none;" st-image="edit" class="logo"></a>
                                            </center>
                                          </td>
                                       </tr>
                                       <!-- Spacing -->
                                       <tr>
                                          <td width="100%" height="10"></td>
                                       </tr>
                                       <!-- Spacing -->
                                    </tbody>
                                 </table>
                              </td>
                           </tr>
                        </tbody>
                     </table>
                  </td>
               </tr>
            </tbody>
         </table>
      </div>

      <div class="block">
         <!-- start textbox-with-title -->
         <table width="100%" bgcolor="#f9fafa" cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="fulltext">
            <tbody>
               <tr>
                  <td>
                     <table bgcolor="#ffffff" width="580" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth" modulebg="edit">
                        <tbody>
                           <!-- Spacing -->
                           <tr>
                              <td width="100%" height="30"></td>
                           </tr>
                           <!-- Spacing -->
                           <tr>
                              <td>
                                 <table width="540" align="center" cellpadding="0" cellspacing="0" border="0" class="devicewidthinner">
                                    <tbody>
                                       <!-- Title -->
                                       <tr>
                                          <td style="font-size: 18px; color: #515f66; text-align:center;line-height: 20px;" st-title="fulltext-title">
                                             {{subject}}
                                          </td>
                                       </tr>
                                       <!-- End of Title -->
                                       <!-- spacing -->
                                       <tr>
                                          <td height="5"></td>
                                       </tr>
                                       <!-- End of spacing -->
                                       <!-- content -->
                                       <tr>
                                          <td style="font-size: 14px; color: #515f66; text-align:center;line-height: 30px;" st-content="fulltext-paragraph">
                                             {{content}}
                                          </td>
                                       </tr>
                                       <tr>
                                          <td style="font-size: 14px; color: #515f66; text-align:center;line-height: 30px;" st-content="fulltext-paragraph">
                                             {{content1}}
                                          </td>
                                       </tr>
                                       <tr>
                                          <td style="font-size: 14px; color: #515f66; text-align:center;line-height: 30px;" st-content="fulltext-paragraph">
                                             {{content2}}
                                          </td>
                                       </tr>
                                       <!-- End of content -->
                                       <!-- Spacing -->
                                       <tr>
                                          <td width="100%" height="10"></td>
                                       </tr>
                                       <!-- Spacing -->
                                       <!-- button -->
                                       <tr>
                                          <td>

                                             <table height="36" align="center" valign="middle" border="0" cellpadding="0" cellspacing="0" class="tablet-button" st-button="edit">
                                                <tbody>
                                                  <tr>
                                                      <td width="auto" align="center" valign="middle" height="36" style=" background-color:#0033a0; border-top-left-radius:2px; border-bottom-left-radius:2px;border-top-right-radius:2px; border-bottom-right-radius:2px; background-clip: padding-box;font-size:13px; text-align:center;  color:#ffffff; font-weight: 500; padding-left:15px; padding-right:15px;">
                                                          <span style="color: #ffffff; font-weight: 300; margin-right: 5px;">
                                                            <a style="color: #ffffff; text-align:center;text-decoration: none;" href="http://app.ritapos.com/">Uygulamayı Tarayıcıda Aç</a>
                                                          </span>
                                                      </td>
                                                  </tr>
                                                  <tr><td width="auto" align="center" valign="middle" height="12"></td></tr>
                                                  <tr>
                                                      <td width="auto" align="center" valign="middle" height="36" style=" background-color:#0033a0; border-top-left-radius:2px; border-bottom-left-radius:2px;border-top-right-radius:2px; border-bottom-right-radius:2px; background-clip: padding-box;font-size:13px; text-align:center;  color:#ffffff; font-weight: 500; padding-left:25px; padding-right:25px;">

                                                          <span style="color: #ffffff; font-weight: 300; margin-right: 5px;">
                                                            <a style="color: #ffffff; text-align:center;text-decoration: none;" href="https://play.google.com/store/apps/details?id=com.id8vei5h6v0nqt10tpxxs">Android Uygulamasını İndir</a>
                                                          </span>
                                                      </td>
                                                  </tr>
                                                  <tr><td width="auto" align="center" valign="middle" height="12"></td></tr>
                                                  <tr>
                                                      <td width="auto" align="center" valign="middle" height="36" style=" background-color:#0033a0; border-top-left-radius:2px; border-bottom-left-radius:2px;border-top-right-radius:2px; border-bottom-right-radius:2px; background-clip: padding-box;font-size:13px; text-align:center;  color:#ffffff; font-weight: 500; padding-left:35px; padding-right:35px;">

                                                          <span style="color: #ffffff; font-weight: 300; margin-right: 5px;">
                                                            <a style="color: #ffffff; text-align:center;text-decoration: none;" href="https://itunes.apple.com/us/app/ritapos/id1225640951?mt=8">IOS Uygulamasını İndir</a>
                                                          </span>
                                                      </td>
                                                   </tr>
                                                   <tr><td width="auto" align="center" valign="middle" height="22"></td></tr>
                                                </tbody>
                                             </table>

                                          </td>
                                       </tr>
                                       <!-- /button -->
                                       <!-- Spacing -->
                                       <tr>
                                          <td width="100%" height="30"></td>
                                       </tr>
                                       <!-- Spacing -->
                                    </tbody>
                                 </table>
                              </td>
                           </tr>
                           <tr>
                            <td colspan="3" align="center" height="1" style="border: 0; margin: 0; padding: 0; font-size: 1px; line-height: 1px; mso-line-height-rule: exactly;">
                              <table align="center" border="0" cellpadding="0" cellspacing="0" width="200">
                                <tbody>
                                <tr>
                                  <td bgcolor="edeff0" style="border: 0; margin: 4px 0; padding: 0; font-size: 1px; line-height: 1px; mso-line-height-rule: exactly;">
                                    <div class="clear" style="height: 1px; width: 200px;">&nbsp;</div>
                                  </td>
                                </tr>
                                </tbody>
                              </table>
                            </td>
                           </tr>
                           <tr>
                            <td width="auto" align="center" valign="middle" height="48">
                              <span style="color: #959fa5; font-weight: 300; font-size: 13px; line-height: 17px; margin-right: 5px;"><br></span>
                            </td>
                           </tr>
                        </tbody>
                     </table>
                  </td>
               </tr>
            </tbody>
         </table>
         <!-- end of textbox-with-title -->
      </div>
   </body>
</html>

```

**Comment by jankapunkt** [comment]
@guncebektas I reproduced it and it seems, that `meteor add spacebars` seems to fix this issue. Please try it on your system and let me know if this is the case for your, too. If this did not work, please update `blaze` to `blaze@2.6.1` and `templating-runtime` to `templating-runtime@1.6.1`. It should work then.

**Comment by guncebektas** [comment]
Yes, it solved the problem @jankapunkt thank you

**Comment by getninjaN** [comment]
This is an issue with 3.0.0 also. Should I open a new issue for it?
